# Generated by Django 4.2.23 on 2025-10-30 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_rating_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('ChatGPT', 'ChatGPT'), ('DeepSeek', 'DeepSeek'), ('LLaMA', 'LLaMA'), ('Claude', 'Claude'), ('Gemini', 'Gemini')], max_length=50)),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='ai_prompt',
            field=models.ForeignKey(blank=True, help_text='AI prompt used to generate this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_posts', to='blog.aiprompt'),
        ),
    ]
