# Generated by Django 4.2.23 on 2025-11-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aiprompt_post_ai_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='model_name',
            field=models.CharField(choices=[('ChatGPT', 'ChatGPT'), ('Gemini', 'Gemini'), ('DeepSeek', 'DeepSeek')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('ChatGPT', 'ChatGPT'), ('Gemini', 'Gemini'), ('DeepSeek', 'DeepSeek')], max_length=50),
        ),
    ]
